language: ruby

install:
  - mkdir ~/bin
  - cd ~/bin && wget "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
  - cd ~/bin && unzip "packer_${PACKER_VERSION}_linux_amd64.zip"
  - ~/bin/packer -v || true
  - export PATH=~/bin:$PATH
  - which packer

script:
  - cd "${TRAVIS_BUILD_DIR}/ubuntu-12.04.4-precise-chef11.10" && packer validate template.json
  - cd "${TRAVIS_BUILD_DIR}/ubuntu-14.04.x-trusty" && packer validate template.json

sudo: false

branches:
  only:
  - master

notification:
  email:
    on_success: never
